####################################
# pt-frontend chart configuration
####################################

# This is to override the chart name.
nameOverride: "pt-frontend"
fullnameOverride: ""

# This will set the replicaset count.
replicaCount: 1

# This sets the container image.
image:
  repository: ghcr.io/bdsc-cds/pt-frontend
  pullPolicy: IfNotPresent
  pullSecrets:
    - name: registry-auth

# This is for setting up a service for the pt-frontend deployment.
service:
  enabled: true
  type: ClusterIP
  port: 16080
  targetPort: 80

# This block is for setting up the ingress for the pt-frontend.
ingress:
  enabled: true
  host: "pt-frontend.rdeid.unil.ch"
  tls: false # Secret name should match: {{ .Chart.Name }}-tls
  className: public
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"

# Configuration   
config:
  - apiUrl: "" # Backend API URL
  - logoFileName: "chuv-logo-white.png" # Filename of the logo to display in the header (usz-logo-white.png, chuv-logo-white.png, sphn-logo-white.png)
  - cssTheme: "chuv-theme" # CSS theme to use (usz-theme, chuv-theme, sphn-theme)

# Deployment specific options
podAnnotations: {}
podLabels: {}
affinity: {}
tolerations: []
nodeSelector: {}
resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi