version: '3'
services:
  react-app-template:
    container_name: react-app-template
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - nodemodules:/usr/src/app/node_modules
    ports:
      - '3000:3000'

volumes:
  nodemodules: {}