apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-frontend-{{ include "chart.nameid" . }}
  labels:
    app: deployment-frontend-{{ include "chart.nameid" . }}
    nameid: { { include "chart.nameid" . } }
    version: { { .Values.version } }
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-frontend-{{ include "chart.nameid" . }}
  template:
    metadata:
      labels:
        app: deployment-frontend-{{ include "chart.nameid" . }}
    spec:
      containers:
        - name: deployment-frontend-{{ include "chart.nameid" . }}
          image: "{{ .Values.image }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: registry-auth
