/* tslint:disable */
/* eslint-disable */
/**
 * pt backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: development.bdsc@chuv.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  RpcStatus,
  TemplatebackendGetConfigReply,
} from '../models/index';
import {
    RpcStatusFromJSON,
    RpcStatusToJSON,
    TemplatebackendGetConfigReplyFromJSON,
    TemplatebackendGetConfigReplyToJSON,
} from '../models/index';

export interface ConfigServiceGetConfigRequest {
    id: number;
}

/**
 * 
 */
export class ConfigurationApi extends runtime.BaseAPI {

    /**
     * This endpoint returns a configuration file for a given user
     * Get a configuration file
     */
    async configServiceGetConfigRaw(requestParameters: ConfigServiceGetConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TemplatebackendGetConfigReply>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling configServiceGetConfig.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/rest/v1/configs/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TemplatebackendGetConfigReplyFromJSON(jsonValue));
    }

    /**
     * This endpoint returns a configuration file for a given user
     * Get a configuration file
     */
    async configServiceGetConfig(requestParameters: ConfigServiceGetConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TemplatebackendGetConfigReply> {
        const response = await this.configServiceGetConfigRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
