/* tslint:disable */
/* eslint-disable */
/**
 * pt backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: development.bdsc@chuv.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  RpcStatus,
  TemplatebackendDeleteDatasetReply,
  TemplatebackendGetDatasetContentReply,
  TemplatebackendGetDatasetMetadataReply,
  TemplatebackendListDatasetsReply,
  TemplatebackendStoreDatasetReply,
  TemplatebackendStoreDatasetRequest,
} from '../models/index';
import {
    RpcStatusFromJSON,
    RpcStatusToJSON,
    TemplatebackendDeleteDatasetReplyFromJSON,
    TemplatebackendDeleteDatasetReplyToJSON,
    TemplatebackendGetDatasetContentReplyFromJSON,
    TemplatebackendGetDatasetContentReplyToJSON,
    TemplatebackendGetDatasetMetadataReplyFromJSON,
    TemplatebackendGetDatasetMetadataReplyToJSON,
    TemplatebackendListDatasetsReplyFromJSON,
    TemplatebackendListDatasetsReplyToJSON,
    TemplatebackendStoreDatasetReplyFromJSON,
    TemplatebackendStoreDatasetReplyToJSON,
    TemplatebackendStoreDatasetRequestFromJSON,
    TemplatebackendStoreDatasetRequestToJSON,
} from '../models/index';

export interface DatasetServiceDeleteDatasetRequest {
    name: string;
}

export interface DatasetServiceGetDatasetContentRequest {
    name: string;
    offset?: number;
    limit?: number;
}

export interface DatasetServiceGetDatasetMetadataRequest {
    name: string;
}

export interface DatasetServiceListDatasetsRequest {
    offset?: number;
    limit?: number;
}

export interface DatasetServiceStoreDatasetRequest {
    body: TemplatebackendStoreDatasetRequest;
}

/**
 * 
 */
export class DatasetApi extends runtime.BaseAPI {

    /**
     * This endpoint deletes a dataset
     * Deletes a dataset
     */
    async datasetServiceDeleteDatasetRaw(requestParameters: DatasetServiceDeleteDatasetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TemplatebackendDeleteDatasetReply>> {
        if (requestParameters.name === null || requestParameters.name === undefined) {
            throw new runtime.RequiredError('name','Required parameter requestParameters.name was null or undefined when calling datasetServiceDeleteDataset.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/v1/dataset/{name}`.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters.name))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TemplatebackendDeleteDatasetReplyFromJSON(jsonValue));
    }

    /**
     * This endpoint deletes a dataset
     * Deletes a dataset
     */
    async datasetServiceDeleteDataset(requestParameters: DatasetServiceDeleteDatasetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TemplatebackendDeleteDatasetReply> {
        const response = await this.datasetServiceDeleteDatasetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This endpoint allow getting a specific user\'s Dataset Content
     * Get Dataset Content
     */
    async datasetServiceGetDatasetContentRaw(requestParameters: DatasetServiceGetDatasetContentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TemplatebackendGetDatasetContentReply>> {
        if (requestParameters.name === null || requestParameters.name === undefined) {
            throw new runtime.RequiredError('name','Required parameter requestParameters.name was null or undefined when calling datasetServiceGetDatasetContent.');
        }

        const queryParameters: any = {};

        if (requestParameters.offset !== undefined) {
            queryParameters['offset'] = requestParameters.offset;
        }

        if (requestParameters.limit !== undefined) {
            queryParameters['limit'] = requestParameters.limit;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/v1/dataset/content/{name}`.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters.name))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TemplatebackendGetDatasetContentReplyFromJSON(jsonValue));
    }

    /**
     * This endpoint allow getting a specific user\'s Dataset Content
     * Get Dataset Content
     */
    async datasetServiceGetDatasetContent(requestParameters: DatasetServiceGetDatasetContentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TemplatebackendGetDatasetContentReply> {
        const response = await this.datasetServiceGetDatasetContentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This endpoint allow getting a specific user\'s Dataset Metadata
     * Get Dataset Metadata
     */
    async datasetServiceGetDatasetMetadataRaw(requestParameters: DatasetServiceGetDatasetMetadataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TemplatebackendGetDatasetMetadataReply>> {
        if (requestParameters.name === null || requestParameters.name === undefined) {
            throw new runtime.RequiredError('name','Required parameter requestParameters.name was null or undefined when calling datasetServiceGetDatasetMetadata.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/v1/dataset/metadata/{name}`.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters.name))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TemplatebackendGetDatasetMetadataReplyFromJSON(jsonValue));
    }

    /**
     * This endpoint allow getting a specific user\'s Dataset Metadata
     * Get Dataset Metadata
     */
    async datasetServiceGetDatasetMetadata(requestParameters: DatasetServiceGetDatasetMetadataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TemplatebackendGetDatasetMetadataReply> {
        const response = await this.datasetServiceGetDatasetMetadataRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This endpoint allows listing a user\'s datasets
     * List datasets
     */
    async datasetServiceListDatasetsRaw(requestParameters: DatasetServiceListDatasetsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TemplatebackendListDatasetsReply>> {
        const queryParameters: any = {};

        if (requestParameters.offset !== undefined) {
            queryParameters['offset'] = requestParameters.offset;
        }

        if (requestParameters.limit !== undefined) {
            queryParameters['limit'] = requestParameters.limit;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/v1/dataset`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TemplatebackendListDatasetsReplyFromJSON(jsonValue));
    }

    /**
     * This endpoint allows listing a user\'s datasets
     * List datasets
     */
    async datasetServiceListDatasets(requestParameters: DatasetServiceListDatasetsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TemplatebackendListDatasetsReply> {
        const response = await this.datasetServiceListDatasetsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This endpoint stores a dataset
     * Store a dataset
     */
    async datasetServiceStoreDatasetRaw(requestParameters: DatasetServiceStoreDatasetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TemplatebackendStoreDatasetReply>> {
        if (requestParameters.body === null || requestParameters.body === undefined) {
            throw new runtime.RequiredError('body','Required parameter requestParameters.body was null or undefined when calling datasetServiceStoreDataset.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/v1/dataset`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TemplatebackendStoreDatasetRequestToJSON(requestParameters.body),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TemplatebackendStoreDatasetReplyFromJSON(jsonValue));
    }

    /**
     * This endpoint stores a dataset
     * Store a dataset
     */
    async datasetServiceStoreDataset(requestParameters: DatasetServiceStoreDatasetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TemplatebackendStoreDatasetReply> {
        const response = await this.datasetServiceStoreDatasetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
