/* tslint:disable */
/* eslint-disable */
/**
 * pt backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: development.bdsc@chuv.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  RpcStatus,
  TemplatebackendCreateQuestionnaireReply,
  TemplatebackendCreateQuestionnaireRequest,
  TemplatebackendDeleteQuestionnaireReply,
  TemplatebackendGetQuestionnaireReply,
  TemplatebackendGetReplyReply,
  TemplatebackendListQuestionnaireReply,
  TemplatebackendListRepliesReply,
} from '../models/index';
import {
    RpcStatusFromJSON,
    RpcStatusToJSON,
    TemplatebackendCreateQuestionnaireReplyFromJSON,
    TemplatebackendCreateQuestionnaireReplyToJSON,
    TemplatebackendCreateQuestionnaireRequestFromJSON,
    TemplatebackendCreateQuestionnaireRequestToJSON,
    TemplatebackendDeleteQuestionnaireReplyFromJSON,
    TemplatebackendDeleteQuestionnaireReplyToJSON,
    TemplatebackendGetQuestionnaireReplyFromJSON,
    TemplatebackendGetQuestionnaireReplyToJSON,
    TemplatebackendGetReplyReplyFromJSON,
    TemplatebackendGetReplyReplyToJSON,
    TemplatebackendListQuestionnaireReplyFromJSON,
    TemplatebackendListQuestionnaireReplyToJSON,
    TemplatebackendListRepliesReplyFromJSON,
    TemplatebackendListRepliesReplyToJSON,
} from '../models/index';

export interface QuestionnaireServiceCreateQuestionnaireRequest {
    body: TemplatebackendCreateQuestionnaireRequest;
}

export interface QuestionnaireServiceDeleteQuestionnaireRequest {
    id: string;
}

export interface QuestionnaireServiceGetQuestionnaireRequest {
    id: number;
}

export interface QuestionnaireServiceGetReplyRequest {
    questionnaireVersionId: number;
    replyId: number;
}

export interface QuestionnaireServiceListQuestionnaireRequest {
    offset?: number;
    limit?: number;
}

export interface QuestionnaireServiceListRepliesRequest {
    questionnaireVersionId: number;
    offset?: number;
    limit?: number;
}

/**
 * 
 */
export class QuestionnaireApi extends runtime.BaseAPI {

    /**
     * This endpoint creates a questionnaire
     * Create a questionnaire
     */
    async questionnaireServiceCreateQuestionnaireRaw(requestParameters: QuestionnaireServiceCreateQuestionnaireRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TemplatebackendCreateQuestionnaireReply>> {
        if (requestParameters.body === null || requestParameters.body === undefined) {
            throw new runtime.RequiredError('body','Required parameter requestParameters.body was null or undefined when calling questionnaireServiceCreateQuestionnaire.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/v1/questionnaire`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TemplatebackendCreateQuestionnaireRequestToJSON(requestParameters.body),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TemplatebackendCreateQuestionnaireReplyFromJSON(jsonValue));
    }

    /**
     * This endpoint creates a questionnaire
     * Create a questionnaire
     */
    async questionnaireServiceCreateQuestionnaire(requestParameters: QuestionnaireServiceCreateQuestionnaireRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TemplatebackendCreateQuestionnaireReply> {
        const response = await this.questionnaireServiceCreateQuestionnaireRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This endpoint creates a questionnaire
     * Create a questionnaire
     */
    async questionnaireServiceDeleteQuestionnaireRaw(requestParameters: QuestionnaireServiceDeleteQuestionnaireRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TemplatebackendDeleteQuestionnaireReply>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling questionnaireServiceDeleteQuestionnaire.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/v1/questionnaire/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TemplatebackendDeleteQuestionnaireReplyFromJSON(jsonValue));
    }

    /**
     * This endpoint creates a questionnaire
     * Create a questionnaire
     */
    async questionnaireServiceDeleteQuestionnaire(requestParameters: QuestionnaireServiceDeleteQuestionnaireRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TemplatebackendDeleteQuestionnaireReply> {
        const response = await this.questionnaireServiceDeleteQuestionnaireRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This endpoint allow getting a single user\'s questionnaire
     * Get questionnaires
     */
    async questionnaireServiceGetQuestionnaireRaw(requestParameters: QuestionnaireServiceGetQuestionnaireRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TemplatebackendGetQuestionnaireReply>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling questionnaireServiceGetQuestionnaire.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/v1/questionnaire/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TemplatebackendGetQuestionnaireReplyFromJSON(jsonValue));
    }

    /**
     * This endpoint allow getting a single user\'s questionnaire
     * Get questionnaires
     */
    async questionnaireServiceGetQuestionnaire(requestParameters: QuestionnaireServiceGetQuestionnaireRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TemplatebackendGetQuestionnaireReply> {
        const response = await this.questionnaireServiceGetQuestionnaireRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This endpoint allows getting a user\'s questionnaires reply
     * Get a questionnaires reply
     */
    async questionnaireServiceGetReplyRaw(requestParameters: QuestionnaireServiceGetReplyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TemplatebackendGetReplyReply>> {
        if (requestParameters.questionnaireVersionId === null || requestParameters.questionnaireVersionId === undefined) {
            throw new runtime.RequiredError('questionnaireVersionId','Required parameter requestParameters.questionnaireVersionId was null or undefined when calling questionnaireServiceGetReply.');
        }

        if (requestParameters.replyId === null || requestParameters.replyId === undefined) {
            throw new runtime.RequiredError('replyId','Required parameter requestParameters.replyId was null or undefined when calling questionnaireServiceGetReply.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/v1/questionnaire/{questionnaireVersionId}/replies/{replyId}`.replace(`{${"questionnaireVersionId"}}`, encodeURIComponent(String(requestParameters.questionnaireVersionId))).replace(`{${"replyId"}}`, encodeURIComponent(String(requestParameters.replyId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TemplatebackendGetReplyReplyFromJSON(jsonValue));
    }

    /**
     * This endpoint allows getting a user\'s questionnaires reply
     * Get a questionnaires reply
     */
    async questionnaireServiceGetReply(requestParameters: QuestionnaireServiceGetReplyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TemplatebackendGetReplyReply> {
        const response = await this.questionnaireServiceGetReplyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This endpoint allows listing a user\'s questionnaires
     * List questionnaires
     */
    async questionnaireServiceListQuestionnaireRaw(requestParameters: QuestionnaireServiceListQuestionnaireRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TemplatebackendListQuestionnaireReply>> {
        const queryParameters: any = {};

        if (requestParameters.offset !== undefined) {
            queryParameters['offset'] = requestParameters.offset;
        }

        if (requestParameters.limit !== undefined) {
            queryParameters['limit'] = requestParameters.limit;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/v1/questionnaire`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TemplatebackendListQuestionnaireReplyFromJSON(jsonValue));
    }

    /**
     * This endpoint allows listing a user\'s questionnaires
     * List questionnaires
     */
    async questionnaireServiceListQuestionnaire(requestParameters: QuestionnaireServiceListQuestionnaireRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TemplatebackendListQuestionnaireReply> {
        const response = await this.questionnaireServiceListQuestionnaireRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This endpoint allows listing a user\'s questionnaires replies
     * List questionnaires replies
     */
    async questionnaireServiceListRepliesRaw(requestParameters: QuestionnaireServiceListRepliesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TemplatebackendListRepliesReply>> {
        if (requestParameters.questionnaireVersionId === null || requestParameters.questionnaireVersionId === undefined) {
            throw new runtime.RequiredError('questionnaireVersionId','Required parameter requestParameters.questionnaireVersionId was null or undefined when calling questionnaireServiceListReplies.');
        }

        const queryParameters: any = {};

        if (requestParameters.offset !== undefined) {
            queryParameters['offset'] = requestParameters.offset;
        }

        if (requestParameters.limit !== undefined) {
            queryParameters['limit'] = requestParameters.limit;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/v1/questionnaire/{questionnaireVersionId}/replies`.replace(`{${"questionnaireVersionId"}}`, encodeURIComponent(String(requestParameters.questionnaireVersionId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TemplatebackendListRepliesReplyFromJSON(jsonValue));
    }

    /**
     * This endpoint allows listing a user\'s questionnaires replies
     * List questionnaires replies
     */
    async questionnaireServiceListReplies(requestParameters: QuestionnaireServiceListRepliesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TemplatebackendListRepliesReply> {
        const response = await this.questionnaireServiceListRepliesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
