version: '3'
services:
  dev:
    container_name: t3-app-dev
    build:
      context: ..
      dockerfile: docker/local.Dockerfile
    # volumes:
    #   - ../frontend/:/app
    #   - ../frontend/node_modules:/app/node_modules
    #   - ../frontend/sysctl.conf:/etc/sysctl.conf
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development

  prod:
    container_name: t3-app-prod
    build:
      context: ..
      dockerfile: docker/prod.Dockerfile
    image: registry.itrcs3-app.intranet.chuv/ds-cicd-template-frontend:latest
    ports:
      - '3001:80'
    environment:
      - NODE_ENV=production
