/* tslint:disable */
/* eslint-disable */
/**
 * pt backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: development.bdsc@chuv.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DatasetServiceUpdateDatasetNameRequest
 */
export interface DatasetServiceUpdateDatasetNameRequest {
    /**
     * 
     * @type {string}
     * @memberof DatasetServiceUpdateDatasetNameRequest
     */
    name?: string;
}

/**
 * Check if a given object implements the DatasetServiceUpdateDatasetNameRequest interface.
 */
export function instanceOfDatasetServiceUpdateDatasetNameRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DatasetServiceUpdateDatasetNameRequestFromJSON(json: any): DatasetServiceUpdateDatasetNameRequest {
    return DatasetServiceUpdateDatasetNameRequestFromJSONTyped(json, false);
}

export function DatasetServiceUpdateDatasetNameRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DatasetServiceUpdateDatasetNameRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function DatasetServiceUpdateDatasetNameRequestToJSON(value?: DatasetServiceUpdateDatasetNameRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
    };
}

