/* tslint:disable */
/* eslint-disable */
/**
 * pt backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: development.bdsc@chuv.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface QuestionnaireServiceShareReplyRequest
 */
export interface QuestionnaireServiceShareReplyRequest {
    /**
     * 
     * @type {number}
     * @memberof QuestionnaireServiceShareReplyRequest
     */
    sharedwithUserid?: number;
}

/**
 * Check if a given object implements the QuestionnaireServiceShareReplyRequest interface.
 */
export function instanceOfQuestionnaireServiceShareReplyRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function QuestionnaireServiceShareReplyRequestFromJSON(json: any): QuestionnaireServiceShareReplyRequest {
    return QuestionnaireServiceShareReplyRequestFromJSONTyped(json, false);
}

export function QuestionnaireServiceShareReplyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): QuestionnaireServiceShareReplyRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'sharedwithUserid': !exists(json, 'sharedwithUserid') ? undefined : json['sharedwithUserid'],
    };
}

export function QuestionnaireServiceShareReplyRequestToJSON(value?: QuestionnaireServiceShareReplyRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'sharedwithUserid': value.sharedwithUserid,
    };
}

