/* tslint:disable */
/* eslint-disable */
/**
 * pt backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: development.bdsc@chuv.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TemplatebackendQuestionnaireQuestionAnswerRulePrefill
 */
export interface TemplatebackendQuestionnaireQuestionAnswerRulePrefill {
    /**
     * 
     * @type {number}
     * @memberof TemplatebackendQuestionnaireQuestionAnswerRulePrefill
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof TemplatebackendQuestionnaireQuestionAnswerRulePrefill
     */
    questionId?: number;
    /**
     * 
     * @type {number}
     * @memberof TemplatebackendQuestionnaireQuestionAnswerRulePrefill
     */
    answerId?: number;
    /**
     * 
     * @type {string}
     * @memberof TemplatebackendQuestionnaireQuestionAnswerRulePrefill
     */
    answerText?: string;
    /**
     * 
     * @type {string}
     * @memberof TemplatebackendQuestionnaireQuestionAnswerRulePrefill
     */
    tmpQuestionUUID?: string;
    /**
     * 
     * @type {string}
     * @memberof TemplatebackendQuestionnaireQuestionAnswerRulePrefill
     */
    tmpAnswerUUID?: string;
    /**
     * 
     * @type {Date}
     * @memberof TemplatebackendQuestionnaireQuestionAnswerRulePrefill
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof TemplatebackendQuestionnaireQuestionAnswerRulePrefill
     */
    updatedAt?: Date;
}

/**
 * Check if a given object implements the TemplatebackendQuestionnaireQuestionAnswerRulePrefill interface.
 */
export function instanceOfTemplatebackendQuestionnaireQuestionAnswerRulePrefill(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TemplatebackendQuestionnaireQuestionAnswerRulePrefillFromJSON(json: any): TemplatebackendQuestionnaireQuestionAnswerRulePrefill {
    return TemplatebackendQuestionnaireQuestionAnswerRulePrefillFromJSONTyped(json, false);
}

export function TemplatebackendQuestionnaireQuestionAnswerRulePrefillFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplatebackendQuestionnaireQuestionAnswerRulePrefill {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'questionId': !exists(json, 'questionId') ? undefined : json['questionId'],
        'answerId': !exists(json, 'answerId') ? undefined : json['answerId'],
        'answerText': !exists(json, 'answerText') ? undefined : json['answerText'],
        'tmpQuestionUUID': !exists(json, 'tmpQuestionUUID') ? undefined : json['tmpQuestionUUID'],
        'tmpAnswerUUID': !exists(json, 'tmpAnswerUUID') ? undefined : json['tmpAnswerUUID'],
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'updatedAt': !exists(json, 'updatedAt') ? undefined : (new Date(json['updatedAt'])),
    };
}

export function TemplatebackendQuestionnaireQuestionAnswerRulePrefillToJSON(value?: TemplatebackendQuestionnaireQuestionAnswerRulePrefill | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'questionId': value.questionId,
        'answerId': value.answerId,
        'answerText': value.answerText,
        'tmpQuestionUUID': value.tmpQuestionUUID,
        'tmpAnswerUUID': value.tmpAnswerUUID,
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updatedAt': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
    };
}

