/* tslint:disable */
/* eslint-disable */
/**
 * pt backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: development.bdsc@chuv.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TemplatebackendSearchUsersRequest
 */
export interface TemplatebackendSearchUsersRequest {
    /**
     * 
     * @type {string}
     * @memberof TemplatebackendSearchUsersRequest
     */
    emailLike?: string;
}

/**
 * Check if a given object implements the TemplatebackendSearchUsersRequest interface.
 */
export function instanceOfTemplatebackendSearchUsersRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TemplatebackendSearchUsersRequestFromJSON(json: any): TemplatebackendSearchUsersRequest {
    return TemplatebackendSearchUsersRequestFromJSONTyped(json, false);
}

export function TemplatebackendSearchUsersRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplatebackendSearchUsersRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'emailLike': !exists(json, 'emailLike') ? undefined : json['emailLike'],
    };
}

export function TemplatebackendSearchUsersRequestToJSON(value?: TemplatebackendSearchUsersRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'emailLike': value.emailLike,
    };
}

