/* tslint:disable */
/* eslint-disable */
/**
 * pt backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: development.bdsc@chuv.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TemplatebackendGetQuestionnaireResult } from './TemplatebackendGetQuestionnaireResult';
import {
    TemplatebackendGetQuestionnaireResultFromJSON,
    TemplatebackendGetQuestionnaireResultFromJSONTyped,
    TemplatebackendGetQuestionnaireResultToJSON,
} from './TemplatebackendGetQuestionnaireResult';

/**
 * 
 * @export
 * @interface TemplatebackendGetQuestionnaireReply
 */
export interface TemplatebackendGetQuestionnaireReply {
    /**
     * 
     * @type {TemplatebackendGetQuestionnaireResult}
     * @memberof TemplatebackendGetQuestionnaireReply
     */
    result?: TemplatebackendGetQuestionnaireResult;
}

/**
 * Check if a given object implements the TemplatebackendGetQuestionnaireReply interface.
 */
export function instanceOfTemplatebackendGetQuestionnaireReply(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TemplatebackendGetQuestionnaireReplyFromJSON(json: any): TemplatebackendGetQuestionnaireReply {
    return TemplatebackendGetQuestionnaireReplyFromJSONTyped(json, false);
}

export function TemplatebackendGetQuestionnaireReplyFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplatebackendGetQuestionnaireReply {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'result': !exists(json, 'result') ? undefined : TemplatebackendGetQuestionnaireResultFromJSON(json['result']),
    };
}

export function TemplatebackendGetQuestionnaireReplyToJSON(value?: TemplatebackendGetQuestionnaireReply | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'result': TemplatebackendGetQuestionnaireResultToJSON(value.result),
    };
}

