/* tslint:disable */
/* eslint-disable */
/**
 * pt backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: development.bdsc@chuv.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TemplatebackendUpdateDatasetNameResult } from './TemplatebackendUpdateDatasetNameResult';
import {
    TemplatebackendUpdateDatasetNameResultFromJSON,
    TemplatebackendUpdateDatasetNameResultFromJSONTyped,
    TemplatebackendUpdateDatasetNameResultToJSON,
} from './TemplatebackendUpdateDatasetNameResult';

/**
 * 
 * @export
 * @interface TemplatebackendUpdateDatasetNameReply
 */
export interface TemplatebackendUpdateDatasetNameReply {
    /**
     * 
     * @type {TemplatebackendUpdateDatasetNameResult}
     * @memberof TemplatebackendUpdateDatasetNameReply
     */
    result?: TemplatebackendUpdateDatasetNameResult;
}

/**
 * Check if a given object implements the TemplatebackendUpdateDatasetNameReply interface.
 */
export function instanceOfTemplatebackendUpdateDatasetNameReply(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TemplatebackendUpdateDatasetNameReplyFromJSON(json: any): TemplatebackendUpdateDatasetNameReply {
    return TemplatebackendUpdateDatasetNameReplyFromJSONTyped(json, false);
}

export function TemplatebackendUpdateDatasetNameReplyFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplatebackendUpdateDatasetNameReply {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'result': !exists(json, 'result') ? undefined : TemplatebackendUpdateDatasetNameResultFromJSON(json['result']),
    };
}

export function TemplatebackendUpdateDatasetNameReplyToJSON(value?: TemplatebackendUpdateDatasetNameReply | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'result': TemplatebackendUpdateDatasetNameResultToJSON(value.result),
    };
}

