/* tslint:disable */
/* eslint-disable */
/**
 * pt backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: development.bdsc@chuv.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TemplatebackendMetadata
 */
export interface TemplatebackendMetadata {
    /**
     * 
     * @type {number}
     * @memberof TemplatebackendMetadata
     */
    userid?: number;
    /**
     * 
     * @type {number}
     * @memberof TemplatebackendMetadata
     */
    tenantid?: number;
    /**
     * 
     * @type {number}
     * @memberof TemplatebackendMetadata
     */
    datasetId?: number;
    /**
     * 
     * @type {number}
     * @memberof TemplatebackendMetadata
     */
    columnId?: number;
    /**
     * 
     * @type {string}
     * @memberof TemplatebackendMetadata
     */
    columnName?: string;
    /**
     * 
     * @type {string}
     * @memberof TemplatebackendMetadata
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof TemplatebackendMetadata
     */
    identifier?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TemplatebackendMetadata
     */
    isId?: boolean;
}

/**
 * Check if a given object implements the TemplatebackendMetadata interface.
 */
export function instanceOfTemplatebackendMetadata(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TemplatebackendMetadataFromJSON(json: any): TemplatebackendMetadata {
    return TemplatebackendMetadataFromJSONTyped(json, false);
}

export function TemplatebackendMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplatebackendMetadata {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userid': !exists(json, 'userid') ? undefined : json['userid'],
        'tenantid': !exists(json, 'tenantid') ? undefined : json['tenantid'],
        'datasetId': !exists(json, 'datasetId') ? undefined : json['datasetId'],
        'columnId': !exists(json, 'columnId') ? undefined : json['columnId'],
        'columnName': !exists(json, 'columnName') ? undefined : json['columnName'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'identifier': !exists(json, 'identifier') ? undefined : json['identifier'],
        'isId': !exists(json, 'isId') ? undefined : json['isId'],
    };
}

export function TemplatebackendMetadataToJSON(value?: TemplatebackendMetadata | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'userid': value.userid,
        'tenantid': value.tenantid,
        'datasetId': value.datasetId,
        'columnId': value.columnId,
        'columnName': value.columnName,
        'type': value.type,
        'identifier': value.identifier,
        'isId': value.isId,
    };
}

