/* tslint:disable */
/* eslint-disable */
/**
 * pt backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: development.bdsc@chuv.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TemplatebackendMetadata } from './TemplatebackendMetadata';
import {
    TemplatebackendMetadataFromJSON,
    TemplatebackendMetadataFromJSONTyped,
    TemplatebackendMetadataToJSON,
} from './TemplatebackendMetadata';

/**
 * 
 * @export
 * @interface TemplatebackendChangeTypesDatasetRequest
 */
export interface TemplatebackendChangeTypesDatasetRequest {
    /**
     * 
     * @type {number}
     * @memberof TemplatebackendChangeTypesDatasetRequest
     */
    datasetId?: number;
    /**
     * 
     * @type {Array<TemplatebackendMetadata>}
     * @memberof TemplatebackendChangeTypesDatasetRequest
     */
    metadata?: Array<TemplatebackendMetadata>;
}

/**
 * Check if a given object implements the TemplatebackendChangeTypesDatasetRequest interface.
 */
export function instanceOfTemplatebackendChangeTypesDatasetRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TemplatebackendChangeTypesDatasetRequestFromJSON(json: any): TemplatebackendChangeTypesDatasetRequest {
    return TemplatebackendChangeTypesDatasetRequestFromJSONTyped(json, false);
}

export function TemplatebackendChangeTypesDatasetRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplatebackendChangeTypesDatasetRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'datasetId': !exists(json, 'datasetId') ? undefined : json['datasetId'],
        'metadata': !exists(json, 'metadata') ? undefined : ((json['metadata'] as Array<any>).map(TemplatebackendMetadataFromJSON)),
    };
}

export function TemplatebackendChangeTypesDatasetRequestToJSON(value?: TemplatebackendChangeTypesDatasetRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'datasetId': value.datasetId,
        'metadata': value.metadata === undefined ? undefined : ((value.metadata as Array<any>).map(TemplatebackendMetadataToJSON)),
    };
}

