/* tslint:disable */
/* eslint-disable */
/**
 * pt backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: development.bdsc@chuv.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TemplatebackendListRepliesResult } from './TemplatebackendListRepliesResult';
import {
    TemplatebackendListRepliesResultFromJSON,
    TemplatebackendListRepliesResultFromJSONTyped,
    TemplatebackendListRepliesResultToJSON,
} from './TemplatebackendListRepliesResult';

/**
 * 
 * @export
 * @interface TemplatebackendListRepliesReply
 */
export interface TemplatebackendListRepliesReply {
    /**
     * 
     * @type {TemplatebackendListRepliesResult}
     * @memberof TemplatebackendListRepliesReply
     */
    result?: TemplatebackendListRepliesResult;
}

/**
 * Check if a given object implements the TemplatebackendListRepliesReply interface.
 */
export function instanceOfTemplatebackendListRepliesReply(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TemplatebackendListRepliesReplyFromJSON(json: any): TemplatebackendListRepliesReply {
    return TemplatebackendListRepliesReplyFromJSONTyped(json, false);
}

export function TemplatebackendListRepliesReplyFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplatebackendListRepliesReply {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'result': !exists(json, 'result') ? undefined : TemplatebackendListRepliesResultFromJSON(json['result']),
    };
}

export function TemplatebackendListRepliesReplyToJSON(value?: TemplatebackendListRepliesReply | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'result': TemplatebackendListRepliesResultToJSON(value.result),
    };
}

