/* tslint:disable */
/* eslint-disable */
/**
 * pt backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: development.bdsc@chuv.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TemplatebackendCreateConfigResult } from './TemplatebackendCreateConfigResult';
import {
    TemplatebackendCreateConfigResultFromJSON,
    TemplatebackendCreateConfigResultFromJSONTyped,
    TemplatebackendCreateConfigResultToJSON,
} from './TemplatebackendCreateConfigResult';

/**
 * 
 * @export
 * @interface TemplatebackendCreateConfigReply
 */
export interface TemplatebackendCreateConfigReply {
    /**
     * 
     * @type {TemplatebackendCreateConfigResult}
     * @memberof TemplatebackendCreateConfigReply
     */
    result?: TemplatebackendCreateConfigResult;
}

/**
 * Check if a given object implements the TemplatebackendCreateConfigReply interface.
 */
export function instanceOfTemplatebackendCreateConfigReply(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TemplatebackendCreateConfigReplyFromJSON(json: any): TemplatebackendCreateConfigReply {
    return TemplatebackendCreateConfigReplyFromJSONTyped(json, false);
}

export function TemplatebackendCreateConfigReplyFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplatebackendCreateConfigReply {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'result': !exists(json, 'result') ? undefined : TemplatebackendCreateConfigResultFromJSON(json['result']),
    };
}

export function TemplatebackendCreateConfigReplyToJSON(value?: TemplatebackendCreateConfigReply | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'result': TemplatebackendCreateConfigResultToJSON(value.result),
    };
}

