/* tslint:disable */
/* eslint-disable */
/**
 * pt backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: development.bdsc@chuv.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TemplatebackendTransformDatasetRequest
 */
export interface TemplatebackendTransformDatasetRequest {
    /**
     * 
     * @type {number}
     * @memberof TemplatebackendTransformDatasetRequest
     */
    datasetId?: number;
    /**
     * 
     * @type {number}
     * @memberof TemplatebackendTransformDatasetRequest
     */
    configId?: number;
}

/**
 * Check if a given object implements the TemplatebackendTransformDatasetRequest interface.
 */
export function instanceOfTemplatebackendTransformDatasetRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TemplatebackendTransformDatasetRequestFromJSON(json: any): TemplatebackendTransformDatasetRequest {
    return TemplatebackendTransformDatasetRequestFromJSONTyped(json, false);
}

export function TemplatebackendTransformDatasetRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplatebackendTransformDatasetRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'datasetId': !exists(json, 'datasetId') ? undefined : json['datasetId'],
        'configId': !exists(json, 'configId') ? undefined : json['configId'],
    };
}

export function TemplatebackendTransformDatasetRequestToJSON(value?: TemplatebackendTransformDatasetRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'datasetId': value.datasetId,
        'configId': value.configId,
    };
}

