/* tslint:disable */
/* eslint-disable */
/**
 * pt backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: development.bdsc@chuv.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TemplatebackendDeleteTransformConfigResult } from './TemplatebackendDeleteTransformConfigResult';
import {
    TemplatebackendDeleteTransformConfigResultFromJSON,
    TemplatebackendDeleteTransformConfigResultFromJSONTyped,
    TemplatebackendDeleteTransformConfigResultToJSON,
} from './TemplatebackendDeleteTransformConfigResult';

/**
 * 
 * @export
 * @interface TemplatebackendDeleteTransformConfigReply
 */
export interface TemplatebackendDeleteTransformConfigReply {
    /**
     * 
     * @type {TemplatebackendDeleteTransformConfigResult}
     * @memberof TemplatebackendDeleteTransformConfigReply
     */
    result?: TemplatebackendDeleteTransformConfigResult;
}

/**
 * Check if a given object implements the TemplatebackendDeleteTransformConfigReply interface.
 */
export function instanceOfTemplatebackendDeleteTransformConfigReply(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TemplatebackendDeleteTransformConfigReplyFromJSON(json: any): TemplatebackendDeleteTransformConfigReply {
    return TemplatebackendDeleteTransformConfigReplyFromJSONTyped(json, false);
}

export function TemplatebackendDeleteTransformConfigReplyFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplatebackendDeleteTransformConfigReply {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'result': !exists(json, 'result') ? undefined : TemplatebackendDeleteTransformConfigResultFromJSON(json['result']),
    };
}

export function TemplatebackendDeleteTransformConfigReplyToJSON(value?: TemplatebackendDeleteTransformConfigReply | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'result': TemplatebackendDeleteTransformConfigResultToJSON(value.result),
    };
}

