/* tslint:disable */
/* eslint-disable */
/**
 * pt backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: development.bdsc@chuv.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TemplatebackendUpdateDatasetResult } from './TemplatebackendUpdateDatasetResult';
import {
    TemplatebackendUpdateDatasetResultFromJSON,
    TemplatebackendUpdateDatasetResultFromJSONTyped,
    TemplatebackendUpdateDatasetResultToJSON,
} from './TemplatebackendUpdateDatasetResult';

/**
 * 
 * @export
 * @interface TemplatebackendUpdateDatasetReply
 */
export interface TemplatebackendUpdateDatasetReply {
    /**
     * 
     * @type {TemplatebackendUpdateDatasetResult}
     * @memberof TemplatebackendUpdateDatasetReply
     */
    result?: TemplatebackendUpdateDatasetResult;
}

/**
 * Check if a given object implements the TemplatebackendUpdateDatasetReply interface.
 */
export function instanceOfTemplatebackendUpdateDatasetReply(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TemplatebackendUpdateDatasetReplyFromJSON(json: any): TemplatebackendUpdateDatasetReply {
    return TemplatebackendUpdateDatasetReplyFromJSONTyped(json, false);
}

export function TemplatebackendUpdateDatasetReplyFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplatebackendUpdateDatasetReply {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'result': !exists(json, 'result') ? undefined : TemplatebackendUpdateDatasetResultFromJSON(json['result']),
    };
}

export function TemplatebackendUpdateDatasetReplyToJSON(value?: TemplatebackendUpdateDatasetReply | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'result': TemplatebackendUpdateDatasetResultToJSON(value.result),
    };
}

