/* tslint:disable */
/* eslint-disable */
/**
 * pt backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: development.bdsc@chuv.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TemplatebackendUserEmail
 */
export interface TemplatebackendUserEmail {
    /**
     * 
     * @type {number}
     * @memberof TemplatebackendUserEmail
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof TemplatebackendUserEmail
     */
    email?: string;
}

/**
 * Check if a given object implements the TemplatebackendUserEmail interface.
 */
export function instanceOfTemplatebackendUserEmail(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TemplatebackendUserEmailFromJSON(json: any): TemplatebackendUserEmail {
    return TemplatebackendUserEmailFromJSONTyped(json, false);
}

export function TemplatebackendUserEmailFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplatebackendUserEmail {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'email': !exists(json, 'email') ? undefined : json['email'],
    };
}

export function TemplatebackendUserEmailToJSON(value?: TemplatebackendUserEmail | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'email': value.email,
    };
}

