/* tslint:disable */
/* eslint-disable */
/**
 * pt backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: development.bdsc@chuv.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TemplatebackendTransformConfig } from './TemplatebackendTransformConfig';
import {
    TemplatebackendTransformConfigFromJSON,
    TemplatebackendTransformConfigFromJSONTyped,
    TemplatebackendTransformConfigToJSON,
} from './TemplatebackendTransformConfig';

/**
 * 
 * @export
 * @interface TemplatebackendCreateTransformConfigRequest
 */
export interface TemplatebackendCreateTransformConfigRequest {
    /**
     * 
     * @type {TemplatebackendTransformConfig}
     * @memberof TemplatebackendCreateTransformConfigRequest
     */
    config?: TemplatebackendTransformConfig;
}

/**
 * Check if a given object implements the TemplatebackendCreateTransformConfigRequest interface.
 */
export function instanceOfTemplatebackendCreateTransformConfigRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TemplatebackendCreateTransformConfigRequestFromJSON(json: any): TemplatebackendCreateTransformConfigRequest {
    return TemplatebackendCreateTransformConfigRequestFromJSONTyped(json, false);
}

export function TemplatebackendCreateTransformConfigRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplatebackendCreateTransformConfigRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'config': !exists(json, 'config') ? undefined : TemplatebackendTransformConfigFromJSON(json['config']),
    };
}

export function TemplatebackendCreateTransformConfigRequestToJSON(value?: TemplatebackendCreateTransformConfigRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'config': TemplatebackendTransformConfigToJSON(value.config),
    };
}

