/* tslint:disable */
/* eslint-disable */
/**
 * pt backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: development.bdsc@chuv.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TemplatebackendGetDatasetJupyterhubResult } from './TemplatebackendGetDatasetJupyterhubResult';
import {
    TemplatebackendGetDatasetJupyterhubResultFromJSON,
    TemplatebackendGetDatasetJupyterhubResultFromJSONTyped,
    TemplatebackendGetDatasetJupyterhubResultToJSON,
} from './TemplatebackendGetDatasetJupyterhubResult';

/**
 * 
 * @export
 * @interface TemplatebackendGetDatasetJupyterhubReply
 */
export interface TemplatebackendGetDatasetJupyterhubReply {
    /**
     * 
     * @type {TemplatebackendGetDatasetJupyterhubResult}
     * @memberof TemplatebackendGetDatasetJupyterhubReply
     */
    result?: TemplatebackendGetDatasetJupyterhubResult;
}

/**
 * Check if a given object implements the TemplatebackendGetDatasetJupyterhubReply interface.
 */
export function instanceOfTemplatebackendGetDatasetJupyterhubReply(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TemplatebackendGetDatasetJupyterhubReplyFromJSON(json: any): TemplatebackendGetDatasetJupyterhubReply {
    return TemplatebackendGetDatasetJupyterhubReplyFromJSONTyped(json, false);
}

export function TemplatebackendGetDatasetJupyterhubReplyFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplatebackendGetDatasetJupyterhubReply {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'result': !exists(json, 'result') ? undefined : TemplatebackendGetDatasetJupyterhubResultFromJSON(json['result']),
    };
}

export function TemplatebackendGetDatasetJupyterhubReplyToJSON(value?: TemplatebackendGetDatasetJupyterhubReply | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'result': TemplatebackendGetDatasetJupyterhubResultToJSON(value.result),
    };
}

