/* tslint:disable */
/* eslint-disable */
/**
 * pt backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: development.bdsc@chuv.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TemplatebackendCreateQuestionnaireVersionResult } from './TemplatebackendCreateQuestionnaireVersionResult';
import {
    TemplatebackendCreateQuestionnaireVersionResultFromJSON,
    TemplatebackendCreateQuestionnaireVersionResultFromJSONTyped,
    TemplatebackendCreateQuestionnaireVersionResultToJSON,
} from './TemplatebackendCreateQuestionnaireVersionResult';

/**
 * 
 * @export
 * @interface TemplatebackendCreateQuestionnaireVersionReply
 */
export interface TemplatebackendCreateQuestionnaireVersionReply {
    /**
     * 
     * @type {TemplatebackendCreateQuestionnaireVersionResult}
     * @memberof TemplatebackendCreateQuestionnaireVersionReply
     */
    result?: TemplatebackendCreateQuestionnaireVersionResult;
}

/**
 * Check if a given object implements the TemplatebackendCreateQuestionnaireVersionReply interface.
 */
export function instanceOfTemplatebackendCreateQuestionnaireVersionReply(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TemplatebackendCreateQuestionnaireVersionReplyFromJSON(json: any): TemplatebackendCreateQuestionnaireVersionReply {
    return TemplatebackendCreateQuestionnaireVersionReplyFromJSONTyped(json, false);
}

export function TemplatebackendCreateQuestionnaireVersionReplyFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplatebackendCreateQuestionnaireVersionReply {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'result': !exists(json, 'result') ? undefined : TemplatebackendCreateQuestionnaireVersionResultFromJSON(json['result']),
    };
}

export function TemplatebackendCreateQuestionnaireVersionReplyToJSON(value?: TemplatebackendCreateQuestionnaireVersionReply | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'result': TemplatebackendCreateQuestionnaireVersionResultToJSON(value.result),
    };
}

