/* tslint:disable */
/* eslint-disable */
/**
 * pt backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: development.bdsc@chuv.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TemplatebackendQuestionnaire } from './TemplatebackendQuestionnaire';
import {
    TemplatebackendQuestionnaireFromJSON,
    TemplatebackendQuestionnaireFromJSONTyped,
    TemplatebackendQuestionnaireToJSON,
} from './TemplatebackendQuestionnaire';

/**
 * 
 * @export
 * @interface TemplatebackendListQuestionnaireResult
 */
export interface TemplatebackendListQuestionnaireResult {
    /**
     * 
     * @type {Array<TemplatebackendQuestionnaire>}
     * @memberof TemplatebackendListQuestionnaireResult
     */
    questionnaires?: Array<TemplatebackendQuestionnaire>;
}

/**
 * Check if a given object implements the TemplatebackendListQuestionnaireResult interface.
 */
export function instanceOfTemplatebackendListQuestionnaireResult(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TemplatebackendListQuestionnaireResultFromJSON(json: any): TemplatebackendListQuestionnaireResult {
    return TemplatebackendListQuestionnaireResultFromJSONTyped(json, false);
}

export function TemplatebackendListQuestionnaireResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplatebackendListQuestionnaireResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'questionnaires': !exists(json, 'questionnaires') ? undefined : ((json['questionnaires'] as Array<any>).map(TemplatebackendQuestionnaireFromJSON)),
    };
}

export function TemplatebackendListQuestionnaireResultToJSON(value?: TemplatebackendListQuestionnaireResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'questionnaires': value.questionnaires === undefined ? undefined : ((value.questionnaires as Array<any>).map(TemplatebackendQuestionnaireToJSON)),
    };
}

