/* tslint:disable */
/* eslint-disable */
/**
 * pt backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: development.bdsc@chuv.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TemplatebackendTransformConfig } from './TemplatebackendTransformConfig';
import {
    TemplatebackendTransformConfigFromJSON,
    TemplatebackendTransformConfigFromJSONTyped,
    TemplatebackendTransformConfigToJSON,
} from './TemplatebackendTransformConfig';

/**
 * 
 * @export
 * @interface TemplatebackendListTransformConfigsResult
 */
export interface TemplatebackendListTransformConfigsResult {
    /**
     * 
     * @type {Array<TemplatebackendTransformConfig>}
     * @memberof TemplatebackendListTransformConfigsResult
     */
    configs?: Array<TemplatebackendTransformConfig>;
}

/**
 * Check if a given object implements the TemplatebackendListTransformConfigsResult interface.
 */
export function instanceOfTemplatebackendListTransformConfigsResult(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TemplatebackendListTransformConfigsResultFromJSON(json: any): TemplatebackendListTransformConfigsResult {
    return TemplatebackendListTransformConfigsResultFromJSONTyped(json, false);
}

export function TemplatebackendListTransformConfigsResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplatebackendListTransformConfigsResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'configs': !exists(json, 'configs') ? undefined : ((json['configs'] as Array<any>).map(TemplatebackendTransformConfigFromJSON)),
    };
}

export function TemplatebackendListTransformConfigsResultToJSON(value?: TemplatebackendListTransformConfigsResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'configs': value.configs === undefined ? undefined : ((value.configs as Array<any>).map(TemplatebackendTransformConfigToJSON)),
    };
}

