/* tslint:disable */
/* eslint-disable */
/**
 * pt backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: development.bdsc@chuv.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TemplatebackendTransformDatasetResult } from './TemplatebackendTransformDatasetResult';
import {
    TemplatebackendTransformDatasetResultFromJSON,
    TemplatebackendTransformDatasetResultFromJSONTyped,
    TemplatebackendTransformDatasetResultToJSON,
} from './TemplatebackendTransformDatasetResult';

/**
 * 
 * @export
 * @interface TemplatebackendTransformDatasetReply
 */
export interface TemplatebackendTransformDatasetReply {
    /**
     * 
     * @type {TemplatebackendTransformDatasetResult}
     * @memberof TemplatebackendTransformDatasetReply
     */
    result?: TemplatebackendTransformDatasetResult;
}

/**
 * Check if a given object implements the TemplatebackendTransformDatasetReply interface.
 */
export function instanceOfTemplatebackendTransformDatasetReply(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TemplatebackendTransformDatasetReplyFromJSON(json: any): TemplatebackendTransformDatasetReply {
    return TemplatebackendTransformDatasetReplyFromJSONTyped(json, false);
}

export function TemplatebackendTransformDatasetReplyFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplatebackendTransformDatasetReply {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'result': !exists(json, 'result') ? undefined : TemplatebackendTransformDatasetResultFromJSON(json['result']),
    };
}

export function TemplatebackendTransformDatasetReplyToJSON(value?: TemplatebackendTransformDatasetReply | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'result': TemplatebackendTransformDatasetResultToJSON(value.result),
    };
}

