/* tslint:disable */
/* eslint-disable */
/**
 * pt backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: development.bdsc@chuv.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TemplatebackendShareReplyResult } from './TemplatebackendShareReplyResult';
import {
    TemplatebackendShareReplyResultFromJSON,
    TemplatebackendShareReplyResultFromJSONTyped,
    TemplatebackendShareReplyResultToJSON,
} from './TemplatebackendShareReplyResult';

/**
 * 
 * @export
 * @interface TemplatebackendShareReplyReply
 */
export interface TemplatebackendShareReplyReply {
    /**
     * 
     * @type {TemplatebackendShareReplyResult}
     * @memberof TemplatebackendShareReplyReply
     */
    result?: TemplatebackendShareReplyResult;
}

/**
 * Check if a given object implements the TemplatebackendShareReplyReply interface.
 */
export function instanceOfTemplatebackendShareReplyReply(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TemplatebackendShareReplyReplyFromJSON(json: any): TemplatebackendShareReplyReply {
    return TemplatebackendShareReplyReplyFromJSONTyped(json, false);
}

export function TemplatebackendShareReplyReplyFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplatebackendShareReplyReply {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'result': !exists(json, 'result') ? undefined : TemplatebackendShareReplyResultFromJSON(json['result']),
    };
}

export function TemplatebackendShareReplyReplyToJSON(value?: TemplatebackendShareReplyReply | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'result': TemplatebackendShareReplyResultToJSON(value.result),
    };
}

