/* tslint:disable */
/* eslint-disable */
/**
 * pt backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: development.bdsc@chuv.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TemplatebackendListQuestionnaireResult } from './TemplatebackendListQuestionnaireResult';
import {
    TemplatebackendListQuestionnaireResultFromJSON,
    TemplatebackendListQuestionnaireResultFromJSONTyped,
    TemplatebackendListQuestionnaireResultToJSON,
} from './TemplatebackendListQuestionnaireResult';

/**
 * 
 * @export
 * @interface TemplatebackendListQuestionnaireReply
 */
export interface TemplatebackendListQuestionnaireReply {
    /**
     * 
     * @type {TemplatebackendListQuestionnaireResult}
     * @memberof TemplatebackendListQuestionnaireReply
     */
    result?: TemplatebackendListQuestionnaireResult;
}

/**
 * Check if a given object implements the TemplatebackendListQuestionnaireReply interface.
 */
export function instanceOfTemplatebackendListQuestionnaireReply(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TemplatebackendListQuestionnaireReplyFromJSON(json: any): TemplatebackendListQuestionnaireReply {
    return TemplatebackendListQuestionnaireReplyFromJSONTyped(json, false);
}

export function TemplatebackendListQuestionnaireReplyFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplatebackendListQuestionnaireReply {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'result': !exists(json, 'result') ? undefined : TemplatebackendListQuestionnaireResultFromJSON(json['result']),
    };
}

export function TemplatebackendListQuestionnaireReplyToJSON(value?: TemplatebackendListQuestionnaireReply | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'result': TemplatebackendListQuestionnaireResultToJSON(value.result),
    };
}

