/* tslint:disable */
/* eslint-disable */
/**
 * pt backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: development.bdsc@chuv.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TemplatebackendExportConfigReply
 */
export interface TemplatebackendExportConfigReply {
    /**
     * 
     * @type {string}
     * @memberof TemplatebackendExportConfigReply
     */
    config?: string;
}

/**
 * Check if a given object implements the TemplatebackendExportConfigReply interface.
 */
export function instanceOfTemplatebackendExportConfigReply(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TemplatebackendExportConfigReplyFromJSON(json: any): TemplatebackendExportConfigReply {
    return TemplatebackendExportConfigReplyFromJSONTyped(json, false);
}

export function TemplatebackendExportConfigReplyFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplatebackendExportConfigReply {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'config': !exists(json, 'config') ? undefined : json['config'],
    };
}

export function TemplatebackendExportConfigReplyToJSON(value?: TemplatebackendExportConfigReply | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'config': value.config,
    };
}

