/* tslint:disable */
/* eslint-disable */
/**
 * pt backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: development.bdsc@chuv.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TemplatebackendGetConfigResult } from './TemplatebackendGetConfigResult';
import {
    TemplatebackendGetConfigResultFromJSON,
    TemplatebackendGetConfigResultFromJSONTyped,
    TemplatebackendGetConfigResultToJSON,
} from './TemplatebackendGetConfigResult';

/**
 * 
 * @export
 * @interface TemplatebackendGetConfigReply
 */
export interface TemplatebackendGetConfigReply {
    /**
     * 
     * @type {TemplatebackendGetConfigResult}
     * @memberof TemplatebackendGetConfigReply
     */
    result?: TemplatebackendGetConfigResult;
}

/**
 * Check if a given object implements the TemplatebackendGetConfigReply interface.
 */
export function instanceOfTemplatebackendGetConfigReply(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TemplatebackendGetConfigReplyFromJSON(json: any): TemplatebackendGetConfigReply {
    return TemplatebackendGetConfigReplyFromJSONTyped(json, false);
}

export function TemplatebackendGetConfigReplyFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplatebackendGetConfigReply {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'result': !exists(json, 'result') ? undefined : TemplatebackendGetConfigResultFromJSON(json['result']),
    };
}

export function TemplatebackendGetConfigReplyToJSON(value?: TemplatebackendGetConfigReply | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'result': TemplatebackendGetConfigResultToJSON(value.result),
    };
}

