/* tslint:disable */
/* eslint-disable */
/**
 * pt backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: development.bdsc@chuv.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TemplatebackendGetConfigsResult } from './TemplatebackendGetConfigsResult';
import {
    TemplatebackendGetConfigsResultFromJSON,
    TemplatebackendGetConfigsResultFromJSONTyped,
    TemplatebackendGetConfigsResultToJSON,
} from './TemplatebackendGetConfigsResult';

/**
 * 
 * @export
 * @interface TemplatebackendGetConfigsReply
 */
export interface TemplatebackendGetConfigsReply {
    /**
     * 
     * @type {TemplatebackendGetConfigsResult}
     * @memberof TemplatebackendGetConfigsReply
     */
    result?: TemplatebackendGetConfigsResult;
}

/**
 * Check if a given object implements the TemplatebackendGetConfigsReply interface.
 */
export function instanceOfTemplatebackendGetConfigsReply(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TemplatebackendGetConfigsReplyFromJSON(json: any): TemplatebackendGetConfigsReply {
    return TemplatebackendGetConfigsReplyFromJSONTyped(json, false);
}

export function TemplatebackendGetConfigsReplyFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplatebackendGetConfigsReply {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'result': !exists(json, 'result') ? undefined : TemplatebackendGetConfigsResultFromJSON(json['result']),
    };
}

export function TemplatebackendGetConfigsReplyToJSON(value?: TemplatebackendGetConfigsReply | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'result': TemplatebackendGetConfigsResultToJSON(value.result),
    };
}

