/* tslint:disable */
/* eslint-disable */
/**
 * pt backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: development.bdsc@chuv.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TemplatebackendDeleteConfigResult } from './TemplatebackendDeleteConfigResult';
import {
    TemplatebackendDeleteConfigResultFromJSON,
    TemplatebackendDeleteConfigResultFromJSONTyped,
    TemplatebackendDeleteConfigResultToJSON,
} from './TemplatebackendDeleteConfigResult';

/**
 * 
 * @export
 * @interface TemplatebackendDeleteConfigReply
 */
export interface TemplatebackendDeleteConfigReply {
    /**
     * 
     * @type {TemplatebackendDeleteConfigResult}
     * @memberof TemplatebackendDeleteConfigReply
     */
    result?: TemplatebackendDeleteConfigResult;
}

/**
 * Check if a given object implements the TemplatebackendDeleteConfigReply interface.
 */
export function instanceOfTemplatebackendDeleteConfigReply(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TemplatebackendDeleteConfigReplyFromJSON(json: any): TemplatebackendDeleteConfigReply {
    return TemplatebackendDeleteConfigReplyFromJSONTyped(json, false);
}

export function TemplatebackendDeleteConfigReplyFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplatebackendDeleteConfigReply {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'result': !exists(json, 'result') ? undefined : TemplatebackendDeleteConfigResultFromJSON(json['result']),
    };
}

export function TemplatebackendDeleteConfigReplyToJSON(value?: TemplatebackendDeleteConfigReply | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'result': TemplatebackendDeleteConfigResultToJSON(value.result),
    };
}

