/* tslint:disable */
/* eslint-disable */
/**
 * pt backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: development.bdsc@chuv.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TemplatebackendDeleteDatasetResult } from './TemplatebackendDeleteDatasetResult';
import {
    TemplatebackendDeleteDatasetResultFromJSON,
    TemplatebackendDeleteDatasetResultFromJSONTyped,
    TemplatebackendDeleteDatasetResultToJSON,
} from './TemplatebackendDeleteDatasetResult';

/**
 * 
 * @export
 * @interface TemplatebackendDeleteDatasetReply
 */
export interface TemplatebackendDeleteDatasetReply {
    /**
     * 
     * @type {TemplatebackendDeleteDatasetResult}
     * @memberof TemplatebackendDeleteDatasetReply
     */
    result?: TemplatebackendDeleteDatasetResult;
}

/**
 * Check if a given object implements the TemplatebackendDeleteDatasetReply interface.
 */
export function instanceOfTemplatebackendDeleteDatasetReply(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TemplatebackendDeleteDatasetReplyFromJSON(json: any): TemplatebackendDeleteDatasetReply {
    return TemplatebackendDeleteDatasetReplyFromJSONTyped(json, false);
}

export function TemplatebackendDeleteDatasetReplyFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplatebackendDeleteDatasetReply {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'result': !exists(json, 'result') ? undefined : TemplatebackendDeleteDatasetResultFromJSON(json['result']),
    };
}

export function TemplatebackendDeleteDatasetReplyToJSON(value?: TemplatebackendDeleteDatasetReply | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'result': TemplatebackendDeleteDatasetResultToJSON(value.result),
    };
}

