/* tslint:disable */
/* eslint-disable */
/**
 * pt backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: development.bdsc@chuv.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TemplatebackendListTransformConfigsResult } from './TemplatebackendListTransformConfigsResult';
import {
    TemplatebackendListTransformConfigsResultFromJSON,
    TemplatebackendListTransformConfigsResultFromJSONTyped,
    TemplatebackendListTransformConfigsResultToJSON,
} from './TemplatebackendListTransformConfigsResult';

/**
 * 
 * @export
 * @interface TemplatebackendListTransformConfigsReply
 */
export interface TemplatebackendListTransformConfigsReply {
    /**
     * 
     * @type {TemplatebackendListTransformConfigsResult}
     * @memberof TemplatebackendListTransformConfigsReply
     */
    result?: TemplatebackendListTransformConfigsResult;
}

/**
 * Check if a given object implements the TemplatebackendListTransformConfigsReply interface.
 */
export function instanceOfTemplatebackendListTransformConfigsReply(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TemplatebackendListTransformConfigsReplyFromJSON(json: any): TemplatebackendListTransformConfigsReply {
    return TemplatebackendListTransformConfigsReplyFromJSONTyped(json, false);
}

export function TemplatebackendListTransformConfigsReplyFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplatebackendListTransformConfigsReply {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'result': !exists(json, 'result') ? undefined : TemplatebackendListTransformConfigsResultFromJSON(json['result']),
    };
}

export function TemplatebackendListTransformConfigsReplyToJSON(value?: TemplatebackendListTransformConfigsReply | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'result': TemplatebackendListTransformConfigsResultToJSON(value.result),
    };
}

