/* tslint:disable */
/* eslint-disable */
/**
 * pt backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: development.bdsc@chuv.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TemplatebackendQuestionnaire } from './TemplatebackendQuestionnaire';
import {
    TemplatebackendQuestionnaireFromJSON,
    TemplatebackendQuestionnaireFromJSONTyped,
    TemplatebackendQuestionnaireToJSON,
} from './TemplatebackendQuestionnaire';

/**
 * 
 * @export
 * @interface TemplatebackendGetQuestionnaireResult
 */
export interface TemplatebackendGetQuestionnaireResult {
    /**
     * 
     * @type {TemplatebackendQuestionnaire}
     * @memberof TemplatebackendGetQuestionnaireResult
     */
    questionnaire?: TemplatebackendQuestionnaire;
}

/**
 * Check if a given object implements the TemplatebackendGetQuestionnaireResult interface.
 */
export function instanceOfTemplatebackendGetQuestionnaireResult(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TemplatebackendGetQuestionnaireResultFromJSON(json: any): TemplatebackendGetQuestionnaireResult {
    return TemplatebackendGetQuestionnaireResultFromJSONTyped(json, false);
}

export function TemplatebackendGetQuestionnaireResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplatebackendGetQuestionnaireResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'questionnaire': !exists(json, 'questionnaire') ? undefined : TemplatebackendQuestionnaireFromJSON(json['questionnaire']),
    };
}

export function TemplatebackendGetQuestionnaireResultToJSON(value?: TemplatebackendGetQuestionnaireResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'questionnaire': TemplatebackendQuestionnaireToJSON(value.questionnaire),
    };
}

