/* tslint:disable */
/* eslint-disable */
/**
 * pt backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: development.bdsc@chuv.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TemplatebackendConfig } from './TemplatebackendConfig';
import {
    TemplatebackendConfigFromJSON,
    TemplatebackendConfigFromJSONTyped,
    TemplatebackendConfigToJSON,
} from './TemplatebackendConfig';

/**
 * 
 * @export
 * @interface TemplatebackendGetConfigResult
 */
export interface TemplatebackendGetConfigResult {
    /**
     * 
     * @type {TemplatebackendConfig}
     * @memberof TemplatebackendGetConfigResult
     */
    config?: TemplatebackendConfig;
}

/**
 * Check if a given object implements the TemplatebackendGetConfigResult interface.
 */
export function instanceOfTemplatebackendGetConfigResult(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TemplatebackendGetConfigResultFromJSON(json: any): TemplatebackendGetConfigResult {
    return TemplatebackendGetConfigResultFromJSONTyped(json, false);
}

export function TemplatebackendGetConfigResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplatebackendGetConfigResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'config': !exists(json, 'config') ? undefined : TemplatebackendConfigFromJSON(json['config']),
    };
}

export function TemplatebackendGetConfigResultToJSON(value?: TemplatebackendGetConfigResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'config': TemplatebackendConfigToJSON(value.config),
    };
}

