/* tslint:disable */
/* eslint-disable */
/**
 * pt backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: development.bdsc@chuv.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TemplatebackendStoreDatasetResult } from './TemplatebackendStoreDatasetResult';
import {
    TemplatebackendStoreDatasetResultFromJSON,
    TemplatebackendStoreDatasetResultFromJSONTyped,
    TemplatebackendStoreDatasetResultToJSON,
} from './TemplatebackendStoreDatasetResult';

/**
 * 
 * @export
 * @interface TemplatebackendStoreDatasetReply
 */
export interface TemplatebackendStoreDatasetReply {
    /**
     * 
     * @type {TemplatebackendStoreDatasetResult}
     * @memberof TemplatebackendStoreDatasetReply
     */
    result?: TemplatebackendStoreDatasetResult;
}

/**
 * Check if a given object implements the TemplatebackendStoreDatasetReply interface.
 */
export function instanceOfTemplatebackendStoreDatasetReply(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TemplatebackendStoreDatasetReplyFromJSON(json: any): TemplatebackendStoreDatasetReply {
    return TemplatebackendStoreDatasetReplyFromJSONTyped(json, false);
}

export function TemplatebackendStoreDatasetReplyFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplatebackendStoreDatasetReply {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'result': !exists(json, 'result') ? undefined : TemplatebackendStoreDatasetResultFromJSON(json['result']),
    };
}

export function TemplatebackendStoreDatasetReplyToJSON(value?: TemplatebackendStoreDatasetReply | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'result': TemplatebackendStoreDatasetResultToJSON(value.result),
    };
}

