/* tslint:disable */
/* eslint-disable */
/**
 * pt backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: development.bdsc@chuv.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TemplatebackendDeleteQuestionnaireResult
 */
export interface TemplatebackendDeleteQuestionnaireResult {
    /**
     * 
     * @type {boolean}
     * @memberof TemplatebackendDeleteQuestionnaireResult
     */
    success?: boolean;
}

/**
 * Check if a given object implements the TemplatebackendDeleteQuestionnaireResult interface.
 */
export function instanceOfTemplatebackendDeleteQuestionnaireResult(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TemplatebackendDeleteQuestionnaireResultFromJSON(json: any): TemplatebackendDeleteQuestionnaireResult {
    return TemplatebackendDeleteQuestionnaireResultFromJSONTyped(json, false);
}

export function TemplatebackendDeleteQuestionnaireResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplatebackendDeleteQuestionnaireResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': !exists(json, 'success') ? undefined : json['success'],
    };
}

export function TemplatebackendDeleteQuestionnaireResultToJSON(value?: TemplatebackendDeleteQuestionnaireResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
    };
}

