/* tslint:disable */
/* eslint-disable */
/**
 * pt backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: development.bdsc@chuv.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TemplatebackendDeleteQuestionnaireResult } from './TemplatebackendDeleteQuestionnaireResult';
import {
    TemplatebackendDeleteQuestionnaireResultFromJSON,
    TemplatebackendDeleteQuestionnaireResultFromJSONTyped,
    TemplatebackendDeleteQuestionnaireResultToJSON,
} from './TemplatebackendDeleteQuestionnaireResult';

/**
 * 
 * @export
 * @interface TemplatebackendDeleteQuestionnaireReply
 */
export interface TemplatebackendDeleteQuestionnaireReply {
    /**
     * 
     * @type {TemplatebackendDeleteQuestionnaireResult}
     * @memberof TemplatebackendDeleteQuestionnaireReply
     */
    result?: TemplatebackendDeleteQuestionnaireResult;
}

/**
 * Check if a given object implements the TemplatebackendDeleteQuestionnaireReply interface.
 */
export function instanceOfTemplatebackendDeleteQuestionnaireReply(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TemplatebackendDeleteQuestionnaireReplyFromJSON(json: any): TemplatebackendDeleteQuestionnaireReply {
    return TemplatebackendDeleteQuestionnaireReplyFromJSONTyped(json, false);
}

export function TemplatebackendDeleteQuestionnaireReplyFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplatebackendDeleteQuestionnaireReply {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'result': !exists(json, 'result') ? undefined : TemplatebackendDeleteQuestionnaireResultFromJSON(json['result']),
    };
}

export function TemplatebackendDeleteQuestionnaireReplyToJSON(value?: TemplatebackendDeleteQuestionnaireReply | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'result': TemplatebackendDeleteQuestionnaireResultToJSON(value.result),
    };
}

