/* tslint:disable */
/* eslint-disable */
/**
 * pt backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: development.bdsc@chuv.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TemplatebackendDateShiftConfig
 */
export interface TemplatebackendDateShiftConfig {
    /**
     * 
     * @type {number}
     * @memberof TemplatebackendDateShiftConfig
     */
    lowrange?: number;
    /**
     * 
     * @type {number}
     * @memberof TemplatebackendDateShiftConfig
     */
    highrange?: number;
}

/**
 * Check if a given object implements the TemplatebackendDateShiftConfig interface.
 */
export function instanceOfTemplatebackendDateShiftConfig(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TemplatebackendDateShiftConfigFromJSON(json: any): TemplatebackendDateShiftConfig {
    return TemplatebackendDateShiftConfigFromJSONTyped(json, false);
}

export function TemplatebackendDateShiftConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplatebackendDateShiftConfig {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'lowrange': !exists(json, 'lowrange') ? undefined : json['lowrange'],
        'highrange': !exists(json, 'highrange') ? undefined : json['highrange'],
    };
}

export function TemplatebackendDateShiftConfigToJSON(value?: TemplatebackendDateShiftConfig | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'lowrange': value.lowrange,
        'highrange': value.highrange,
    };
}

