/* tslint:disable */
/* eslint-disable */
/**
 * pt backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: development.bdsc@chuv.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TemplatebackendGetDatasetJupyterhubResult
 */
export interface TemplatebackendGetDatasetJupyterhubResult {
    /**
     * 
     * @type {string}
     * @memberof TemplatebackendGetDatasetJupyterhubResult
     */
    url?: string;
}

/**
 * Check if a given object implements the TemplatebackendGetDatasetJupyterhubResult interface.
 */
export function instanceOfTemplatebackendGetDatasetJupyterhubResult(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TemplatebackendGetDatasetJupyterhubResultFromJSON(json: any): TemplatebackendGetDatasetJupyterhubResult {
    return TemplatebackendGetDatasetJupyterhubResultFromJSONTyped(json, false);
}

export function TemplatebackendGetDatasetJupyterhubResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplatebackendGetDatasetJupyterhubResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'url': !exists(json, 'url') ? undefined : json['url'],
    };
}

export function TemplatebackendGetDatasetJupyterhubResultToJSON(value?: TemplatebackendGetDatasetJupyterhubResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'url': value.url,
    };
}

