/* tslint:disable */
/* eslint-disable */
/**
 * pt backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: development.bdsc@chuv.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TemplatebackendCreateQuestionnaireVersionResult
 */
export interface TemplatebackendCreateQuestionnaireVersionResult {
    /**
     * 
     * @type {number}
     * @memberof TemplatebackendCreateQuestionnaireVersionResult
     */
    id?: number;
}

/**
 * Check if a given object implements the TemplatebackendCreateQuestionnaireVersionResult interface.
 */
export function instanceOfTemplatebackendCreateQuestionnaireVersionResult(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TemplatebackendCreateQuestionnaireVersionResultFromJSON(json: any): TemplatebackendCreateQuestionnaireVersionResult {
    return TemplatebackendCreateQuestionnaireVersionResultFromJSONTyped(json, false);
}

export function TemplatebackendCreateQuestionnaireVersionResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplatebackendCreateQuestionnaireVersionResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function TemplatebackendCreateQuestionnaireVersionResultToJSON(value?: TemplatebackendCreateQuestionnaireVersionResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
    };
}

