/* tslint:disable */
/* eslint-disable */
/**
 * pt backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: development.bdsc@chuv.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TemplatebackendGetRiskAssessmentResult } from './TemplatebackendGetRiskAssessmentResult';
import {
    TemplatebackendGetRiskAssessmentResultFromJSON,
    TemplatebackendGetRiskAssessmentResultFromJSONTyped,
    TemplatebackendGetRiskAssessmentResultToJSON,
} from './TemplatebackendGetRiskAssessmentResult';

/**
 * 
 * @export
 * @interface TemplatebackendGetRiskAssessmentReply
 */
export interface TemplatebackendGetRiskAssessmentReply {
    /**
     * 
     * @type {TemplatebackendGetRiskAssessmentResult}
     * @memberof TemplatebackendGetRiskAssessmentReply
     */
    result?: TemplatebackendGetRiskAssessmentResult;
}

/**
 * Check if a given object implements the TemplatebackendGetRiskAssessmentReply interface.
 */
export function instanceOfTemplatebackendGetRiskAssessmentReply(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TemplatebackendGetRiskAssessmentReplyFromJSON(json: any): TemplatebackendGetRiskAssessmentReply {
    return TemplatebackendGetRiskAssessmentReplyFromJSONTyped(json, false);
}

export function TemplatebackendGetRiskAssessmentReplyFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplatebackendGetRiskAssessmentReply {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'result': !exists(json, 'result') ? undefined : TemplatebackendGetRiskAssessmentResultFromJSON(json['result']),
    };
}

export function TemplatebackendGetRiskAssessmentReplyToJSON(value?: TemplatebackendGetRiskAssessmentReply | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'result': TemplatebackendGetRiskAssessmentResultToJSON(value.result),
    };
}

