/* tslint:disable */
/* eslint-disable */
/**
 * pt backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: development.bdsc@chuv.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TemplatebackendColumn } from './TemplatebackendColumn';
import {
    TemplatebackendColumnFromJSON,
    TemplatebackendColumnFromJSONTyped,
    TemplatebackendColumnToJSON,
} from './TemplatebackendColumn';

/**
 * 
 * @export
 * @interface TemplatebackendTransformDatasetResult
 */
export interface TemplatebackendTransformDatasetResult {
    /**
     * 
     * @type {Array<TemplatebackendColumn>}
     * @memberof TemplatebackendTransformDatasetResult
     */
    columns?: Array<TemplatebackendColumn>;
}

/**
 * Check if a given object implements the TemplatebackendTransformDatasetResult interface.
 */
export function instanceOfTemplatebackendTransformDatasetResult(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TemplatebackendTransformDatasetResultFromJSON(json: any): TemplatebackendTransformDatasetResult {
    return TemplatebackendTransformDatasetResultFromJSONTyped(json, false);
}

export function TemplatebackendTransformDatasetResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplatebackendTransformDatasetResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'columns': !exists(json, 'columns') ? undefined : ((json['columns'] as Array<any>).map(TemplatebackendColumnFromJSON)),
    };
}

export function TemplatebackendTransformDatasetResultToJSON(value?: TemplatebackendTransformDatasetResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'columns': value.columns === undefined ? undefined : ((value.columns as Array<any>).map(TemplatebackendColumnToJSON)),
    };
}

