/* tslint:disable */
/* eslint-disable */
/**
 * pt backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: development.bdsc@chuv.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TemplatebackendQuestionnaireQuestionReply
 */
export interface TemplatebackendQuestionnaireQuestionReply {
    /**
     * 
     * @type {number}
     * @memberof TemplatebackendQuestionnaireQuestionReply
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof TemplatebackendQuestionnaireQuestionReply
     */
    questionnaireQuestionId?: number;
    /**
     * 
     * @type {string}
     * @memberof TemplatebackendQuestionnaireQuestionReply
     */
    answer?: string;
    /**
     * 
     * @type {Date}
     * @memberof TemplatebackendQuestionnaireQuestionReply
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof TemplatebackendQuestionnaireQuestionReply
     */
    updatedAt?: Date;
}

/**
 * Check if a given object implements the TemplatebackendQuestionnaireQuestionReply interface.
 */
export function instanceOfTemplatebackendQuestionnaireQuestionReply(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TemplatebackendQuestionnaireQuestionReplyFromJSON(json: any): TemplatebackendQuestionnaireQuestionReply {
    return TemplatebackendQuestionnaireQuestionReplyFromJSONTyped(json, false);
}

export function TemplatebackendQuestionnaireQuestionReplyFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplatebackendQuestionnaireQuestionReply {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'questionnaireQuestionId': !exists(json, 'questionnaireQuestionId') ? undefined : json['questionnaireQuestionId'],
        'answer': !exists(json, 'answer') ? undefined : json['answer'],
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'updatedAt': !exists(json, 'updatedAt') ? undefined : (new Date(json['updatedAt'])),
    };
}

export function TemplatebackendQuestionnaireQuestionReplyToJSON(value?: TemplatebackendQuestionnaireQuestionReply | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'questionnaireQuestionId': value.questionnaireQuestionId,
        'answer': value.answer,
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updatedAt': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
    };
}

