/* tslint:disable */
/* eslint-disable */
/**
 * pt backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: development.bdsc@chuv.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TemplatebackendCreateTransformConfigResult } from './TemplatebackendCreateTransformConfigResult';
import {
    TemplatebackendCreateTransformConfigResultFromJSON,
    TemplatebackendCreateTransformConfigResultFromJSONTyped,
    TemplatebackendCreateTransformConfigResultToJSON,
} from './TemplatebackendCreateTransformConfigResult';

/**
 * 
 * @export
 * @interface TemplatebackendCreateTransformConfigReply
 */
export interface TemplatebackendCreateTransformConfigReply {
    /**
     * 
     * @type {TemplatebackendCreateTransformConfigResult}
     * @memberof TemplatebackendCreateTransformConfigReply
     */
    result?: TemplatebackendCreateTransformConfigResult;
}

/**
 * Check if a given object implements the TemplatebackendCreateTransformConfigReply interface.
 */
export function instanceOfTemplatebackendCreateTransformConfigReply(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TemplatebackendCreateTransformConfigReplyFromJSON(json: any): TemplatebackendCreateTransformConfigReply {
    return TemplatebackendCreateTransformConfigReplyFromJSONTyped(json, false);
}

export function TemplatebackendCreateTransformConfigReplyFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplatebackendCreateTransformConfigReply {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'result': !exists(json, 'result') ? undefined : TemplatebackendCreateTransformConfigResultFromJSON(json['result']),
    };
}

export function TemplatebackendCreateTransformConfigReplyToJSON(value?: TemplatebackendCreateTransformConfigReply | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'result': TemplatebackendCreateTransformConfigResultToJSON(value.result),
    };
}

