/* tslint:disable */
/* eslint-disable */
/**
 * pt backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: development.bdsc@chuv.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TemplatebackendUserEmail } from './TemplatebackendUserEmail';
import {
    TemplatebackendUserEmailFromJSON,
    TemplatebackendUserEmailFromJSONTyped,
    TemplatebackendUserEmailToJSON,
} from './TemplatebackendUserEmail';

/**
 * 
 * @export
 * @interface TemplatebackendSearchUsersReply
 */
export interface TemplatebackendSearchUsersReply {
    /**
     * 
     * @type {Array<TemplatebackendUserEmail>}
     * @memberof TemplatebackendSearchUsersReply
     */
    result?: Array<TemplatebackendUserEmail>;
}

/**
 * Check if a given object implements the TemplatebackendSearchUsersReply interface.
 */
export function instanceOfTemplatebackendSearchUsersReply(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TemplatebackendSearchUsersReplyFromJSON(json: any): TemplatebackendSearchUsersReply {
    return TemplatebackendSearchUsersReplyFromJSONTyped(json, false);
}

export function TemplatebackendSearchUsersReplyFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplatebackendSearchUsersReply {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'result': !exists(json, 'result') ? undefined : ((json['result'] as Array<any>).map(TemplatebackendUserEmailFromJSON)),
    };
}

export function TemplatebackendSearchUsersReplyToJSON(value?: TemplatebackendSearchUsersReply | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'result': value.result === undefined ? undefined : ((value.result as Array<any>).map(TemplatebackendUserEmailToJSON)),
    };
}

