/* tslint:disable */
/* eslint-disable */
/**
 * pt backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: development.bdsc@chuv.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TemplatebackendListDatasetsResult } from './TemplatebackendListDatasetsResult';
import {
    TemplatebackendListDatasetsResultFromJSON,
    TemplatebackendListDatasetsResultFromJSONTyped,
    TemplatebackendListDatasetsResultToJSON,
} from './TemplatebackendListDatasetsResult';

/**
 * 
 * @export
 * @interface TemplatebackendListDatasetsReply
 */
export interface TemplatebackendListDatasetsReply {
    /**
     * 
     * @type {TemplatebackendListDatasetsResult}
     * @memberof TemplatebackendListDatasetsReply
     */
    result?: TemplatebackendListDatasetsResult;
}

/**
 * Check if a given object implements the TemplatebackendListDatasetsReply interface.
 */
export function instanceOfTemplatebackendListDatasetsReply(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TemplatebackendListDatasetsReplyFromJSON(json: any): TemplatebackendListDatasetsReply {
    return TemplatebackendListDatasetsReplyFromJSONTyped(json, false);
}

export function TemplatebackendListDatasetsReplyFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplatebackendListDatasetsReply {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'result': !exists(json, 'result') ? undefined : TemplatebackendListDatasetsResultFromJSON(json['result']),
    };
}

export function TemplatebackendListDatasetsReplyToJSON(value?: TemplatebackendListDatasetsReply | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'result': TemplatebackendListDatasetsResultToJSON(value.result),
    };
}

