/* tslint:disable */
/* eslint-disable */
/**
 * pt backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: development.bdsc@chuv.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TemplatebackendScrambleFieldConfig
 */
export interface TemplatebackendScrambleFieldConfig {
    /**
     * 
     * @type {Array<string>}
     * @memberof TemplatebackendScrambleFieldConfig
     */
    fields?: Array<string>;
}

/**
 * Check if a given object implements the TemplatebackendScrambleFieldConfig interface.
 */
export function instanceOfTemplatebackendScrambleFieldConfig(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TemplatebackendScrambleFieldConfigFromJSON(json: any): TemplatebackendScrambleFieldConfig {
    return TemplatebackendScrambleFieldConfigFromJSONTyped(json, false);
}

export function TemplatebackendScrambleFieldConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplatebackendScrambleFieldConfig {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'fields': !exists(json, 'fields') ? undefined : json['fields'],
    };
}

export function TemplatebackendScrambleFieldConfigToJSON(value?: TemplatebackendScrambleFieldConfig | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'fields': value.fields,
    };
}

