/* tslint:disable */
/* eslint-disable */
/**
 * pt backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: development.bdsc@chuv.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TemplatebackendGetRiskAssessmentResult
 */
export interface TemplatebackendGetRiskAssessmentResult {
    /**
     * 
     * @type {Array<string>}
     * @memberof TemplatebackendGetRiskAssessmentResult
     */
    riskAssessment?: Array<string>;
}

/**
 * Check if a given object implements the TemplatebackendGetRiskAssessmentResult interface.
 */
export function instanceOfTemplatebackendGetRiskAssessmentResult(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TemplatebackendGetRiskAssessmentResultFromJSON(json: any): TemplatebackendGetRiskAssessmentResult {
    return TemplatebackendGetRiskAssessmentResultFromJSONTyped(json, false);
}

export function TemplatebackendGetRiskAssessmentResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplatebackendGetRiskAssessmentResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'riskAssessment': !exists(json, 'RiskAssessment') ? undefined : json['RiskAssessment'],
    };
}

export function TemplatebackendGetRiskAssessmentResultToJSON(value?: TemplatebackendGetRiskAssessmentResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'RiskAssessment': value.riskAssessment,
    };
}

