{{- if .Values.config.logopngb64 | default (.Files.Get "files/logo.png") }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-logo
binaryData:
  logo.png: {{ .Values.config.logopngb64 | default (.Files.Get "files/logo.png" | b64enc) }}
{{- end }}
